apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza
spec:
  replicas: 10
  selector:
    matchLabels:
      app: piazza
  template:
    metadata:
      labels:
        app: piazza
    spec:
      containers:
      - name: piazza
        image: ahnafbbk/piazza
        ports:
        - containerPort: 3000

---
  
apiVersion: v1
kind: Service
metadata:
  name: piazza
spec:
  selector:
    app: piazza
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
